export const APP_NAME = 'AI Aggregator';

export const RATE_LIMIT_WINDOWS = {
  MINUTE: 60,
  HOUR: 3600,
  DAY: 86400,
} as const;

export const DEFAULT_LIMITS = {
  ANONYMOUS_REQUESTS_PER_MINUTE: 10,
  USER_REQUESTS_PER_MINUTE: 60,
  API_KEY_REQUESTS_PER_MINUTE: 600,
  SIGNUPS_PER_IP_PER_DAY: 5,
  TOPUPS_PER_USER_PER_HOUR: 10,
} as const;

export const RISK_WEIGHTS = {
  VPN_DETECTED: 15,
  TOR_DETECTED: 40,
  PROXY_DETECTED: 20,
  DATACENTER_IP: 10,
  DISPOSABLE_EMAIL: 30,
  HIGH_VELOCITY_SIGNUP: 25,
  HIGH_VELOCITY_REQUESTS: 20,
  HIGH_VELOCITY_TOPUP: 30,
  MULTI_ACCOUNT_FINGERPRINT: 35,
  MULTI_ACCOUNT_IP: 20,
  MULTI_ACCOUNT_PAYMENT: 40,
  STOLEN_CARD_PATTERN: 80,
  IMPOSSIBLE_TRAVEL: 35,
  PROMPT_ABUSE: 30,
  MODERATION_VIOLATION: 25,
  ABNORMAL_TOKEN_USAGE: 25,
  CHARGEBACK: 70,
  CAPTCHA_FAILED: 15,
  MANUAL_FLAG: 50,
} as const;
